apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-automatic-ingress-certificate-generator
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager-automatic-ingress-certificate-generator
    app.kubernetes.io/instance: generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager-automatic-ingress-certificate-generator
      app.kubernetes.io/instance: generator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cert-manager-automatic-ingress-certificate-generator
        app.kubernetes.io/instance: generator
    spec:
      serviceAccountName: cert-manager-automatic-ingress-certificate-generator
      securityContext: {}
      containers:
      - name: cert-manager-automatic-ingress-certificate-generator
        securityContext: {}
        image: neutryno/cert-manager-automatic-ingress-certificate-generator:latest
        imagePullPolicy: IfNotPresent
        args: []
        env:
        - name: CLUSTER_ISSUERS
          value: "cluster-issuer-1,cluster-issuer-2"
        - name: CLUSTER_ISSUER_1_REGEX
          value: "(.*)\\.dev\\.cloud\\.domain\\.de"
        - name: CLUSTER_ISSUER_2_REGEX
          value: "(.*)\\.test\\.cloud\\.domain\\.de"
        resources: {}
