apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-automatic-ingress-certificate-generator
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-automatic-ingress-certificate-generator
rules:
- apiGroups: [ "" ] # "" indicates the core API group
  resources: [ "namespaces" ]
  verbs: [ "get", "watch", "list" ]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "watch", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-automatic-ingress-certificate-generator
roleRef:
  kind: ClusterRole
  name: cert-manager-automatic-ingress-certificate-generator
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: cert-manager-automatic-ingress-certificate-generator
  namespace: cert-manager
